### PR TITLE
Version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by gkoz** [comment]
It should work correctly after a rebase.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by gkoz** [comment]
Apparently I've failed to remove the `sys` submodule properly?

**Comment by GuillaumeGomez** [comment]
No idea... I did:

``` bash
git remote add upstream https://github.com/gkoz/release
git fetch upstream
git rebase -i upstream/master
```

Do you see anything incorrect?

**Comment by gkoz** [comment]
Actually the problem is from cloning gir and its tests. This is a bit silly :(

**Comment by GuillaumeGomez** [comment]
Dark magic is back!

**Comment by GuillaumeGomez** [comment]
Any change on your side?

**Comment by gkoz** [comment]
I'm making another script ;)

**Comment by gkoz** [comment]
To sidestep the cargo problem we'll have to bump the sys crates versions to 0.3.1 I'm afraid.

**Comment by GuillaumeGomez** [comment]
Ok...

**Comment by GuillaumeGomez** [comment]
I guess tests can be restarted.

**Comment by gkoz** [comment]
I've opened #4 with the new script

**Comment by GuillaumeGomez** [comment]
Great!

**Pull request closed without merging**
